image: registry.gitlab.com/sodaru/container/sodaru/ci-nodejs

stages:
  - test
  - publish

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules

before_script:
  - npm i --ignore-scripts
  - lerna bootstrap
  - lerna run build --stream

test:
  stage: test
  script:
    - npm run check-sanity
    - lerna run test --stream
  only:
    - "develop"

publish:
  stage: publish
  script:
    - npm run check-sanity
    - git diff ./packages/serverless-schema/bin/serverless-schema.js
    - git describe --exact-match | grep ^v && lerna publish from-git --yes
  only:
    - tags
