# yaml-language-server: $schema=../node_modules/somod-schema/schemas/ui-config/index.json

env: {}
imageDomains: []
publicRuntimeConfig:
  defaultThemeOptions:
    SOMOD::Parameter: ui.theme.options

serverRuntimeConfig: {}
